/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Env.Constants;
import java.sql.SQLException;
import helpers.Config;
import helpers.Dialogs;
import helpers.Forms;
import java.awt.BorderLayout;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import models.DB;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author qwerty
 */
public class frmPrincipal extends javax.swing.JFrame {

    private String user_adm;

    public frmPrincipal(String UserName) throws Exception {
        initComponents();
        Traduz();
        setUser(UserName);
        rbPTBR.setSelected((Config.getLang() == Constants.PT_BR));
        rbENUS.setSelected((Config.getLang() == Constants.EN_US));
    }

    public void setUser(String UserName) {
        ResourceBundle props = null;
        props = Config.getResources();
        lblUser.setText(props.getString("cadUser") + ": " + UserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        btn_cad_funcionario = new javax.swing.JButton();
        btntrocar = new javax.swing.JButton();
        btnponto = new javax.swing.JButton();
        btnrelex = new javax.swing.JButton();
        btnfponto = new javax.swing.JButton();
        btnrel_pay = new javax.swing.JButton();
        iashd = new javax.swing.JLabel();
        lbldesc = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        iashd1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        btnCadastro = new javax.swing.JMenu();
        cadUser = new javax.swing.JMenuItem();
        cadFun = new javax.swing.JMenuItem();
        abaPonto = new javax.swing.JMenu();
        regponto = new javax.swing.JMenuItem();
        abaRelatorio = new javax.swing.JMenu();
        rel_func = new javax.swing.JMenuItem();
        rel_ponto = new javax.swing.JMenuItem();
        rel_users = new javax.swing.JMenuItem();
        rel_holerite = new javax.swing.JMenuItem();
        btnHEx = new javax.swing.JMenuItem();
        btnPags = new javax.swing.JMenuItem();
        abaIdioma = new javax.swing.JMenu();
        rbPTBR = new javax.swing.JRadioButtonMenuItem();
        rbENUS = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHX Principal");
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(63, 27, 32));

        jToolBar2.setBackground(new java.awt.Color(93, 93, 93));
        jToolBar2.setRollover(true);

        btn_cad_funcionario.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btn_cad_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcB.png"))); // NOI18N
        btn_cad_funcionario.setText("Cadastrar Funcionario");
        btn_cad_funcionario.setFocusable(false);
        btn_cad_funcionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cad_funcionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cad_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cad_funcionarioActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_cad_funcionario);

        btntrocar.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btntrocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cgUs.png"))); // NOI18N
        btntrocar.setText("Trocar Usuario");
        btntrocar.setFocusable(false);
        btntrocar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntrocar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrocarActionPerformed(evt);
            }
        });
        jToolBar2.add(btntrocar);

        btnponto.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnponto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pontoB.png"))); // NOI18N
        btnponto.setText("Registrar Ponto");
        btnponto.setFocusable(false);
        btnponto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnponto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpontoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnponto);

        btnrelex.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnrelex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hrExB.png"))); // NOI18N
        btnrelex.setText("Relatorio Horas Extras");
        btnrelex.setFocusable(false);
        btnrelex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrelex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrelex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrelexActionPerformed(evt);
            }
        });
        jToolBar2.add(btnrelex);

        btnfponto.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnfponto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fpontoB.png"))); // NOI18N
        btnfponto.setText("Folha de Ponto");
        btnfponto.setFocusable(false);
        btnfponto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfponto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnfponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfpontoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnfponto);

        btnrel_pay.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        btnrel_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/msB.png"))); // NOI18N
        btnrel_pay.setText("Relatorio de Pagamentos");
        btnrel_pay.setFocusable(false);
        btnrel_pay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrel_pay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrel_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrel_payActionPerformed(evt);
            }
        });
        jToolBar2.add(btnrel_pay);

        desktopPane.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 1440, 90);

        iashd.setBackground(new java.awt.Color(254, 254, 254));
        iashd.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        iashd.setForeground(new java.awt.Color(254, 254, 254));
        iashd.setText("v1.0.5");
        desktopPane.add(iashd);
        iashd.setBounds(1270, 100, 90, 30);

        lbldesc.setBackground(new java.awt.Color(254, 254, 254));
        lbldesc.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lbldesc.setForeground(new java.awt.Color(254, 254, 254));
        lbldesc.setText("Sistema de Controle de Horas Extras");
        desktopPane.add(lbldesc);
        lbldesc.setBounds(10, 130, 280, 17);

        lblUser.setBackground(new java.awt.Color(254, 254, 254));
        lblUser.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(254, 254, 254));
        lblUser.setText("Usuario:<usuario>");
        desktopPane.add(lblUser);
        lblUser.setBounds(10, 170, 170, 20);

        iashd1.setBackground(new java.awt.Color(254, 254, 254));
        iashd1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        iashd1.setForeground(new java.awt.Color(254, 254, 254));
        iashd1.setText("SHX");
        desktopPane.add(iashd1);
        iashd1.setBounds(10, 97, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(-520, 40, 2050, 1110);

        menuBar.setBackground(new java.awt.Color(100, 98, 98));

        btnCadastro.setBackground(new java.awt.Color(254, 254, 254));
        btnCadastro.setForeground(new java.awt.Color(254, 254, 254));
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrosBar.png"))); // NOI18N
        btnCadastro.setText("Cadastros");

        cadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userS.png"))); // NOI18N
        cadUser.setText("Usuarios");
        cadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadUserActionPerformed(evt);
            }
        });
        btnCadastro.add(cadUser);

        cadFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcS.png"))); // NOI18N
        cadFun.setText("Funcionarios");
        cadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFunActionPerformed(evt);
            }
        });
        btnCadastro.add(cadFun);

        menuBar.add(btnCadastro);

        abaPonto.setBackground(new java.awt.Color(254, 254, 254));
        abaPonto.setForeground(new java.awt.Color(254, 254, 254));
        abaPonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pontoBar.png"))); // NOI18N
        abaPonto.setMnemonic('e');
        abaPonto.setText("Ponto");

        regponto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pontoS.png"))); // NOI18N
        regponto.setMnemonic('t');
        regponto.setText("Registrar Ponto");
        abaPonto.add(regponto);

        menuBar.add(abaPonto);

        abaRelatorio.setBackground(new java.awt.Color(254, 254, 254));
        abaRelatorio.setForeground(new java.awt.Color(254, 254, 254));
        abaRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reps.png"))); // NOI18N
        abaRelatorio.setMnemonic('h');
        abaRelatorio.setText("Relatorios");

        rel_func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userR.png"))); // NOI18N
        rel_func.setMnemonic('c');
        rel_func.setText("Funcionarios");
        rel_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_funcActionPerformed(evt);
            }
        });
        abaRelatorio.add(rel_func);

        rel_ponto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fponto.png"))); // NOI18N
        rel_ponto.setMnemonic('a');
        rel_ponto.setText("Folha de Ponto");
        rel_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_pontoActionPerformed(evt);
            }
        });
        abaRelatorio.add(rel_ponto);

        rel_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emp.png"))); // NOI18N
        rel_users.setMnemonic('a');
        rel_users.setText("Usuarios");
        rel_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_usersActionPerformed(evt);
            }
        });
        abaRelatorio.add(rel_users);

        rel_holerite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/holerite.png"))); // NOI18N
        rel_holerite.setMnemonic('a');
        rel_holerite.setText("Holerite");
        rel_holerite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_holeriteActionPerformed(evt);
            }
        });
        abaRelatorio.add(rel_holerite);

        btnHEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hrEx.png"))); // NOI18N
        btnHEx.setMnemonic('a');
        btnHEx.setText("Horas Extras");
        btnHEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHExActionPerformed(evt);
            }
        });
        abaRelatorio.add(btnHEx);

        btnPags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mns.png"))); // NOI18N
        btnPags.setMnemonic('a');
        btnPags.setText("Pagamentos");
        btnPags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagsActionPerformed(evt);
            }
        });
        abaRelatorio.add(btnPags);

        menuBar.add(abaRelatorio);

        abaIdioma.setBackground(new java.awt.Color(254, 254, 254));
        abaIdioma.setForeground(new java.awt.Color(254, 254, 254));
        abaIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flag.png"))); // NOI18N
        abaIdioma.setText("Idioma");

        rbPTBR.setText("Portugues pt-br");
        rbPTBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ptbr.png"))); // NOI18N
        rbPTBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPTBRActionPerformed(evt);
            }
        });
        abaIdioma.add(rbPTBR);

        rbENUS.setText("Ingles en-us");
        rbENUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enus.png"))); // NOI18N
        rbENUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbENUSActionPerformed(evt);
            }
        });
        abaIdioma.add(rbENUS);

        menuBar.add(abaIdioma);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpontoActionPerformed
        if (Env.Constants.ObjUser.getAdmin()) {
            infrmPonto objPnt = new infrmPonto(this.desktopPane);
            Forms.showInternal(desktopPane, objPnt);
        } else {
            Dialogs.showError(user_adm);
        }
    }//GEN-LAST:event_btnpontoActionPerformed

    private void btn_cad_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_funcionarioActionPerformed
        cadFun.doClick();
    }//GEN-LAST:event_btn_cad_funcionarioActionPerformed

    private void btnrelexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrelexActionPerformed
        // TODO add your handling code here:
        btnHEx.doClick();
    }//GEN-LAST:event_btnrelexActionPerformed

    private void rbENUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbENUSActionPerformed

        try {
            Locale en = new Locale("en", "US");

            Locale.setDefault(en);

            Config.setLang(Constants.EN_US);

            this.Traduz();

            rbPTBR.setSelected(false);

        } catch (SQLException ex) {
            Dialogs.showError(ex.getMessage());
        }
    }//GEN-LAST:event_rbENUSActionPerformed

    private void rbPTBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPTBRActionPerformed

        try {
            Locale Pt = new Locale("pt", "BR");

            Locale.setDefault(Pt);

            Config.setLang(Constants.PT_BR);

            this.Traduz();

            rbENUS.setSelected(false);
        } catch (SQLException ex) {
            Dialogs.showError(ex.getMessage());
        }
    }//GEN-LAST:event_rbPTBRActionPerformed

    private void cadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFunActionPerformed
        infrmCadFun objFun = new infrmCadFun();
        Forms.showInternal(desktopPane, objFun);
    }//GEN-LAST:event_cadFunActionPerformed

    private void cadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadUserActionPerformed
        // TODO add your handling code here:
        frmCadUsuario objCadUser = new frmCadUsuario(true);
        objCadUser.setAlwaysOnTop(true);
        objCadUser.setVisible(true);
    }//GEN-LAST:event_cadUserActionPerformed

    private void rel_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_funcActionPerformed

        if (Env.Constants.ObjUser.getAdmin()) {
            try {
                //Pegando-se a conexão do banco

                //Pegando-se o arquivo do relatorio
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_Todos_Funcionarios.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }


    }//GEN-LAST:event_rel_funcActionPerformed

    private void rel_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_usersActionPerformed

        if (Env.Constants.ObjUser.getAdmin()) {

            try {
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_Todos_Funcionarios.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_rel_usersActionPerformed

    private void btntrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrocarActionPerformed
        try {
            // TODO add your handling code here:
            new frmLogin(this).setVisible(true);
        } catch (SQLException ex) {
            Dialogs.showError(ex.getMessage());
        }
    }//GEN-LAST:event_btntrocarActionPerformed

    private void rel_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_pontoActionPerformed

        if (Env.Constants.ObjUser.getAdmin()) {

            try {
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_Folha_de_Ponto.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }
    }//GEN-LAST:event_rel_pontoActionPerformed

    private void btnHExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHExActionPerformed

        if (Env.Constants.ObjUser.getAdmin()) {

            try {
                //Pegando-se a conexão do banco
                //Pegando-se o arquivo do relatorio
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_Principal.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnHExActionPerformed

    private void btnPagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagsActionPerformed

        if (Env.Constants.ObjUser.getAdmin()) {

            try {
                //Pegando-se a conexão do banco
                //Pegando-se o arquivo do relatorio
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_recebidoPorFuncionario.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagsActionPerformed

    private void rel_holeriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_holeriteActionPerformed
        if (Env.Constants.ObjUser.getAdmin()) {

            try {
                //Pegando-se a conexão do banco
                //Pegando-se o arquivo do relatorio
                InputStream inputStream = getClass().getResourceAsStream("../Relatorio/Relatorio_Principal.jasper");

                //Caso seja necessário relatório parametrizado
                Map parametros = new HashMap();

                //usando uma conexão
                JasperPrint print = JasperFillManager.fillReport(inputStream, parametros, DB.Connect());

                JRViewer viewer = new JRViewer(print);

                //Criar o jFrame
                JFrame frameRelatorio = new JFrame("Janela de relatorio");

                //adiciona o JRViewer no JFram
                frameRelatorio.add(viewer, BorderLayout.CENTER);

                //configura o tamanho padrão da Jframe
                frameRelatorio.setSize(500, 500);

                //Maximiza o JFrame para ocupar a tela toda.
                frameRelatorio.setExtendedState(JFrame.MAXIMIZED_BOTH);

                //configura a operação padrao quando o jframe for fechado.
                frameRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                //exibi em tela Jframe
                frameRelatorio.setVisible(true);

            } catch (Exception ex) {
                Dialogs.showError(ex.getMessage());
            }
        } else {
            Dialogs.showError(user_adm);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_rel_holeriteActionPerformed

    private void btnfpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfpontoActionPerformed
        // TODO add your handling code here:
        rel_ponto.doClick();
    }//GEN-LAST:event_btnfpontoActionPerformed

    private void btnrel_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrel_payActionPerformed
        // TODO add your handling code here:
        btnPags.doClick();
    }//GEN-LAST:event_btnrel_payActionPerformed

    public void Traduz() {

        ResourceBundle props = null;
        props = Config.getResources();
        btnCadastro.setText(props.getString("btnCadastro"));
        cadUser.setText(props.getString("cadUser") + "s");
        cadFun.setText(props.getString("cadFun") + "s");
        abaPonto.setText(props.getString("ponto"));
        regponto.setText(props.getString("assinar_ponto"));
        abaRelatorio.setText(props.getString("abaRelatorio"));
        rel_func.setText(props.getString("cadFun") + "s");
        rel_ponto.setText(props.getString("folhaponto"));
        rel_users.setText(props.getString("cadUser") + "s");
        rel_holerite.setText(props.getString("holerite"));
        abaIdioma.setText(props.getString("abaIdioma"));

        btntrocar.setText(props.getString("trocar_user"));
        btn_cad_funcionario.setText(props.getString("btn_cad_func"));
        btnponto.setText(props.getString("assinar_ponto"));
        btnrelex.setText(props.getString("rel_horas_extras"));
        btnfponto.setText(props.getString("folhaponto"));
        btnrel_pay.setText(props.getString("rel_pags"));
        btnHEx.setText(props.getString("horas_extras"));
        btnPags.setText(props.getString("pagamentos"));

        rbENUS.setText(props.getString("enus"));
        rbPTBR.setText(props.getString("ptbr"));

        lbldesc.setText(props.getString("sisdesc"));

        this.setTitle("SHX " + props.getString("maintitle"));

        user_adm = props.getString("user_adm");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abaIdioma;
    private javax.swing.JMenu abaPonto;
    private javax.swing.JMenu abaRelatorio;
    private javax.swing.JMenu btnCadastro;
    private javax.swing.JMenuItem btnHEx;
    private javax.swing.JMenuItem btnPags;
    private javax.swing.JButton btn_cad_funcionario;
    private javax.swing.JButton btnfponto;
    private javax.swing.JButton btnponto;
    private javax.swing.JButton btnrel_pay;
    private javax.swing.JButton btnrelex;
    private javax.swing.JButton btntrocar;
    private javax.swing.JMenuItem cadFun;
    private javax.swing.JMenuItem cadUser;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel iashd;
    private javax.swing.JLabel iashd1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbldesc;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButtonMenuItem rbENUS;
    private javax.swing.JRadioButtonMenuItem rbPTBR;
    private javax.swing.JMenuItem regponto;
    private javax.swing.JMenuItem rel_func;
    private javax.swing.JMenuItem rel_holerite;
    private javax.swing.JMenuItem rel_ponto;
    private javax.swing.JMenuItem rel_users;
    // End of variables declaration//GEN-END:variables

}
