/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.FuncionarioController;
import helpers.Dialogs;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Funcionario;

/**
 *
 * @author qwerty
 */
public class infrmCadFun extends javax.swing.JInternalFrame {

    private FuncionarioController m_FuncC = null;
    private String CPF_CADASTRADO, FUNCIONARIO_INSERIDO_SUCESS, FUNCINOARIO_EDITADO_SUCESS, BTN_NOVO, BTN_SALVAR;
    private Funcionario m_objFunc = null;

    /**
     * Creates new form infrmCadFun
     */
    public void Traduz() {
        CPF_CADASTRADO = "CPF ja cadastrado em outro funcionario!";
        FUNCIONARIO_INSERIDO_SUCESS = "Funcionario inserido com Sucesso!";
        FUNCINOARIO_EDITADO_SUCESS = "Funcionario editado com Sucesso!";
        BTN_NOVO = "Novo";
        BTN_SALVAR = "Salvar";
    }

    private void defaultLayout(boolean dl) {
        btnCancelar.setEnabled(!dl);
        btnNovo.setText((dl) ? BTN_NOVO : BTN_SALVAR);
        txtNome.setText("");
        txtCPF.setText("");
        txtSalario.setText("");
        txtHoraBase.setText("");
        lblValorHoraT.setText("0,00 R$/h");
        txtNome.setEnabled(!dl);
        txtCPF.setEnabled(!dl);
        txtSalario.setEnabled(!dl);
        txtHoraBase.setEnabled(!dl);
        if (dl) {
            loadTable();
        }
    }

    private void loadTable() {
        try {
            m_FuncC = new FuncionarioController();
            List<Funcionario> lstFor = m_FuncC.getAll();
            DefaultTableModel tablemd = (DefaultTableModel) tbFunc.getModel();
            tablemd.getDataVector().removeAllElements();
            if (lstFor.size() > 0) {
                for (Funcionario forn : lstFor) {
                    tablemd.addRow(new Object[]{forn.getNome(), forn.getSalario(), forn.getValor_hora()});
                }
                tbFunc.clearSelection();
            }
            tbFunc.updateUI();
        } catch (Exception ex) {
            Dialogs.showError(ex.getMessage());
        }
    }

    private void InserirFuncionario() throws Exception {
        m_FuncC = new FuncionarioController();
        m_FuncC.Add(txtNome.getText(), txtCPF.getText(), Double.parseDouble(txtSalario.getText()), Integer.valueOf(txtHoraBase.getText()));
        defaultLayout(true);
        Dialogs.showInfo(FUNCIONARIO_INSERIDO_SUCESS);
    }

    private boolean FuncionarioDuplicado() throws Exception {
        m_FuncC = new FuncionarioController();
        if (m_FuncC == null) {
            Funcionario objFunc = m_FuncC.SearchFuncionarioByCPF(txtCPF.getText());
            if (objFunc != null) {
                Dialogs.showWarning(CPF_CADASTRADO);
            }
            return (objFunc != null);
        } else if (m_FuncC.DuplicatedFuncionario(m_objFunc.getId(), txtCPF.getText())) {
            Dialogs.showWarning(CPF_CADASTRADO);
            return true;
        } else {
            return false;
        }
    }

    public infrmCadFun() {
        initComponents();
        Traduz();
        defaultLayout(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        lblValorHora = new javax.swing.JLabel();
        lblHoraBase = new javax.swing.JLabel();
        txtHoraBase = new javax.swing.JTextField();
        lblValorHoraT = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFunc = new javax.swing.JTable();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("SHX Funcionarios");

        lblNome.setText("Nome");

        lblCPF.setText("CPF");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblSalario.setText("Salario");

        lblValorHora.setText("Valor Hora");

        lblHoraBase.setText("Hora Base");

        lblValorHoraT.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblValorHoraT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorHoraT.setText("Valor Hora");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        tbFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Salario", "V. Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbFunc);
        if (tbFunc.getColumnModel().getColumnCount() > 0) {
            tbFunc.getColumnModel().getColumn(0).setMinWidth(250);
            tbFunc.getColumnModel().getColumn(0).setPreferredWidth(250);
            tbFunc.getColumnModel().getColumn(0).setMaxWidth(250);
            tbFunc.getColumnModel().getColumn(1).setMinWidth(130);
            tbFunc.getColumnModel().getColumn(1).setPreferredWidth(130);
            tbFunc.getColumnModel().getColumn(1).setMaxWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblCPF)
                    .addComponent(lblSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtCPF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraBase)
                                    .addComponent(lblValorHora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorHoraT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHoraBase))))
                        .addGap(19, 19, 19))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF)
                    .addComponent(txtHoraBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario)
                    .addComponent(lblValorHora)
                    .addComponent(lblValorHoraT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        try {
            if (btnNovo.getText().equals(BTN_SALVAR)) {
                if (m_objFunc == null) {
                } else if (!FuncionarioDuplicado()) {
                    m_FuncC.Edit(m_objFunc.getId(), txtNome.getText(), txtCPF.getText(),
                            Double.parseDouble(txtSalario.getText()), Integer.valueOf(txtHoraBase.getText()));
                    Dialogs.showInfo(FUNCINOARIO_EDITADO_SUCESS);
                    m_objFunc = null;
                    defaultLayout(true);
                }
            } else if (btnNovo.getText().equals(BTN_NOVO)) {
                defaultLayout(false);
                txtNome.requestFocus();
            }
        } catch (Exception ex) {
            Dialogs.showError(ex.getMessage());
        }
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblHoraBase;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JLabel lblValorHoraT;
    private javax.swing.JTable tbFunc;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtHoraBase;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
