/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.FuncionarioController;
import helpers.Config;
import helpers.Dialogs;
import helpers.Formats;
import java.sql.SQLException;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.Funcionario;

/**
 *
 * @author qwerty
 */
public class infrmConsFunc extends javax.swing.JInternalFrame {

    private infrmPonto out_Ponto;
    private frmPrincipal out_Principal;
    public int m_codFunc;
    private FuncionarioController m_FuncC;
    private int Id_Func = 0;

    public void Traduz() {
        ResourceBundle rbl = null;
        rbl = Config.getResources();
        lblFunc.setText(rbl.getString("cadFun"));

        tbFunc.getColumnModel().getColumn(1).setHeaderValue(rbl.getString("cadFun"));
        tbFunc.getColumnModel().getColumn(2).setHeaderValue(rbl.getString("cpf"));
    }

    private void loadTable() {
        try {

            m_FuncC = new FuncionarioController();
            List<Funcionario> lstFor = null;
            if (txtFuncionario.getText().equals("")) {
                lstFor = m_FuncC.getAll();
            } else {
                lstFor = m_FuncC.SearchFuncionarioByName(txtFuncionario.getText());
            }
            DefaultTableModel tablemd = (DefaultTableModel) tbFunc.getModel();
            tablemd.getDataVector().removeAllElements();
            if (lstFor.size() > 0) {
                for (Funcionario forn : lstFor) {
                    tablemd.addRow(new Object[]{forn.getId(), forn.getNome(), Formats.CPF.Format(forn.getCPF())});
                }
                tbFunc.clearSelection();
            }
            tbFunc.updateUI();
        } catch (Exception ex) {
            Dialogs.showError(ex.getMessage());
        }
    }

    private void runApp() {
        initComponents();
        Traduz();
        loadTable();

    }

    public infrmConsFunc(infrmPonto out_frmPonto) {
        this.out_Ponto = out_frmPonto;
        runApp();
    }

    public infrmConsFunc(frmPrincipal out_frmPrincipal) {
        this.out_Principal = out_frmPrincipal;
        runApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFunc = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFunc = new javax.swing.JTable();

        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setClosable(true);
        setTitle("SHX Consultar Func");
        setName("infrmConsFunc"); // NOI18N

        lblFunc.setText("Funcionario");

        txtFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFuncionarioKeyReleased(evt);
            }
        });

        tbFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Funcionario", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFunc);
        if (tbFunc.getColumnModel().getColumnCount() > 0) {
            tbFunc.getColumnModel().getColumn(0).setMinWidth(30);
            tbFunc.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbFunc.getColumnModel().getColumn(0).setMaxWidth(30);
            tbFunc.getColumnModel().getColumn(1).setMinWidth(300);
            tbFunc.getColumnModel().getColumn(1).setPreferredWidth(300);
            tbFunc.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblFunc)
                .addGap(6, 6, 6)
                .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncMouseClicked
        // TODO add your handling code here:
        try {
            if (evt.getClickCount() > 1) {
                if ((this.out_Ponto != null) && (this.out_Principal == null)) {
                    this.out_Ponto.m_objFunc = new FuncionarioController().getByID(((Integer) tbFunc.getModel().getValueAt(tbFunc.getSelectedRow(), 0)));
                    this.out_Ponto.setFuncionario(this.out_Ponto.m_objFunc.getNome());
                } else if ((this.out_Ponto == null) && (this.out_Principal != null)) {
                    this.out_Principal.relFolhaPonto(((Integer) tbFunc.getModel().getValueAt(tbFunc.getSelectedRow(), 0)));
                }

                this.dispose();
            }
        } catch (SQLException ex) {
            Dialogs.showInfo(ex.getMessage());
        }
    }//GEN-LAST:event_tbFuncMouseClicked

    private void txtFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFuncionarioKeyReleased
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_txtFuncionarioKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JTable tbFunc;
    private javax.swing.JTextField txtFuncionario;
    // End of variables declaration//GEN-END:variables
}
