/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import helpers.Config;
import java.util.ResourceBundle;

/**
 *
 * @author qwerty
 */
public class infrmProgress extends javax.swing.JInternalFrame {

    public void Traduz() {
        ResourceBundle rbl = null;
        rbl = Config.getResources();
    }

    public void doProgress(int goTo) {
        for (int i = pbRel.getValue(); i < goTo; i++) {
            pbRel.setValue(i);
            if (i == 100) {
                this.dispose();
            }

        }

    }

    public infrmProgress() {
        initComponents();
        Traduz();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFunc = new javax.swing.JLabel();
        pbRel = new javax.swing.JProgressBar();

        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setTitle("SHX Consultar Func");
        setName("infrmConsFunc"); // NOI18N

        lblFunc.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblFunc.setText("Carregando relatorio ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFunc)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFunc;
    private javax.swing.JProgressBar pbRel;
    // End of variables declaration//GEN-END:variables
}
